#!/bin/sh

set -e

HOSTNAME="ShaneSpace-Live"
CONFIG_DIR="$(realpath ./config)"

# run config
lb config noauto \
  --architectures amd64 \
  --linux-flavours amd64 \
  --apt-indices false \
  --distribution buster \
  --debian-installer live \
  --debootstrap-options "--variant=minbase" \
  --apt-recommends false \
  --archive-areas "main contrib non-free" \
  --bootappend-live "boot=live components noautologin timezone=America/New_York quiet splash hostname=$HOSTNAME" \
  --bootappend-install "theme=Windows-10-Dark" \
  --debian-installer live \
  --debian-installer-gui true \
  --iso-application ShaneSpaceOS \
  --iso-preparer Shane-https://shanespace.net \
  --iso-publisher Shane-https://shanespace.net \
  --iso-volume ShaneSpaceOS \
  --mirror-bootstrap=http://ftp.us.debian.org/debian \
  hostname=$HOSTNAME \
  "${@}"

# extract icons
tar -zxvf ./config/includes.chroot/usr/share/icons/Windows-10.tar.gz -C ./config/includes.chroot/usr/share/icons/
rm ./config/includes.chroot/usr/share/icons/Windows-10.tar.gz

# add symbolic links
ln -sf /usr/share/graphics/logo_shanespaceos.png ${CONFIG_DIR}/includes.installer/usr/share/graphics/logo_installer.png
ln -sf /usr/share/graphics/logo_shanespaceos_dark.png ${CONFIG_DIR}/includes.installer/usr/share/graphics/logo_installer_dark.png
ln -sf /lib/conky/themes/fancy.conf ${CONFIG_DIR}/includes.chroot/etc/skel/.conkyrc 

# copy skel to root
cp -rT ./config/includes.chroot/etc/skel ./config/includes.chroot/root

# copy theme to installer
mkdir -p ./config/includes.installer/usr/share/themes/Windows-10-Dark
cp -r ./config/includes.chroot/usr/share/themes/Windows-10-Dark/gtk-2.0 ./config/includes.installer/usr/share/themes/Windows-10-Dark/gtk-2.0

