#!/bin/sh

set -e

HOSTNAME="ShaneSpace-Live"

# Update current working directory to dist directory
mkdir -p ./work
cd ./work

# config_check="./.build/config"
# [ -f "${config_check}" ] && { echo "config already completed."; return; }

# run config
lb config noauto \
  --architectures amd64 \
  --linux-flavours amd64 \
  --apt-indices false \
  --distribution buster \
  --debian-installer live \
  --debootstrap-options "--variant=minbase" \
  --apt-recommends false \
  --archive-areas "main contrib non-free" \
  --bootappend-live "boot=live components noautologin timezone=America/New_York quiet splash hostname=ShaneSpaceOS" \
  --iso-application ShaneSpaceOS \
  --iso-preparer Shane-https://shanespace.net \
  --iso-publisher Shane-https://shanespace.net \
  --iso-volume ShaneSpaceOS \
  --mirror-bootstrap=http://ftp.us.debian.org/debian
  hostname=$HOSTNAME \
  "${@}"

# --interactive shell \
# live-config.user-default-groups=audio,cdrom,dip,floppy,video,plugdev,netdev,powerdev,scanner,bluetooth,fuse

# extract icons
tar -zxvf config/includes.chroot/usr/share/icons/Windows-10.tar.gz -C config/includes.chroot/usr/share/icons/
rm config/includes.chroot/usr/share/icons/Windows-10.tar.gz