#!/bin/bash
set -e

LIVE_BUILD_TMP="/tmp2"
mkdir -p "$LIVE_BUILD_TMP"

#######################################
# User functions
#######################################

# create user with default password
add_user()
{
	local username="$1"
	[ -z "$username" ] &&
	{
		echo "Missing required argument \"username\"";
		return 1;
	}
	
	local fullname="$2"
	
	if ! getent passwd "$username"
	then
		echo "Adding user ${username}"
		adduser --disabled-login --gecos "$fullname,,," "$username"
		set_password "$username"
	else
		echo "User \"$username\" already exists."
	fi
	
	return 0
}

add_sudo_user()
{
	local username="$1"
	local fullname="$2"
	
	add_user "$username" "$fullname"
	echo "Adding user ${username} to sudo group"
	usermod -aG sudo "$username"
}

# set user password
set_password()
{
	local username="$1"
	[ -z "$username" ] &&
	{
		echo "Missing required argument \"username\"";
		return 1;
	}
	
	local password="${2:-$username}"
	
	echo "Setting password for ${username}"
	echo "${username}:${password}" | chpasswd
}

#######################################
# Gernic functions
#######################################
get_http_file()
{
	local url="$1"
	[ -z "$url" ] &&
	{
		echo "Missing required argument \"url\"";
		return 1;
	}
	local filename="$(basename $url)"
	
	if [ -f "$LIVE_BUILD_TMP/$filename" ]
	then
	{
		echo "Using cached copy of $filename"
	}
	else
	{
		echo "Downloading \"filename\" from \"$url\""
		wget -nv -O "$LIVE_BUILD_TMP/$filename" "$url"
	}
	fi
}

apt_install_http()
{
	local url="$1"
	[ -z "$url" ] &&
	{
		echo "Missing required argument \"url\"";
		return 1;
	}
	local filename="$(basename $url)"
	
	get_http_file "$url"
	sudo apt install "$LIVE_BUILD_TMP/$filename" -y
}

copy()
{
	local src="$1"
	local destination="$2"
	
	mkdir -p "$(dirname "$destination")"
	echo "Copying file(s) from [$src] to [$destination]"
	rsync -rah --info=progress2 "$src" "$destination"
}

sslink()
{
	local src
	src="$(realpath -s "$1")"
	local destination="$2"
	local output=""
	
	mkdir -p "$(dirname "$destination")"
	echo "Creating symlink from [$src] to [$destination]"
	ln -sfT "$src" "$destination"
}